/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

public class Calculator {
  public String getGreeting() {
    return "Hello World!";
  }

  public Integer add(Integer a, Integer b) {
    return a + b;
  }

  public static void main(String[] args) {
    System.out.println(new Calculator().getGreeting());
  }
}
