/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class LeapYear {
  public Boolean checkLeap(Integer inputYear) {
    if (inputYear % 400 == 0) {
      return true;
    } else if (inputYear % 4 == 0 && inputYear % 100 != 0) {
      return true;
    } else {
      return false;
    }
  }

  public static void main(String[] args) {
    LeapYear leapYear = new LeapYear();

    for (Integer i = 1990; i <= 2030; i++) {
      if (leapYear.checkLeap(i)) {
        System.out.printf("%d is Leap\n", i);
      } else {
        System.out.printf("%d is NOT Leap\n", i);
      }
    }
  }
}
