/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import static org.junit.Assert.*;

public class LeapYearTest {

  @Test
  public void yearDivisibleBy400IsLeap() {
    LeapYear year = new LeapYear();

    assertTrue(year.checkLeap(800));
  }

  @Test
  public void yearDivisibleBy100ButNotBy400IsLeap() {
    LeapYear year = new LeapYear();

    assertTrue(year.checkLeap(2004));
  }

  @Test
  public void yearNotDivisibleBy4IsNotLeap() {
    LeapYear year = new LeapYear();

    assertFalse(year.checkLeap(2009));
  }

  @Test
  public void yearNotDivisibleBy100ButNotby400IsNotLeap() {
    LeapYear year = new LeapYear();

    assertFalse(year.checkLeap(1700));
  }

}
