/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package shoppinglist;

import org.junit.Test;
import static org.junit.Assert.*;

public class ShoppingListTest {
  @Test
  public void testShoppingListIsEmpty() {
    ShoppingList shoppingList = new ShoppingList();

    assertTrue(shoppingList.getItems().isEmpty());
  }

  @Test
  public void testItemsAddedCanBeRetrieved() {
    ShoppingList shoppingList = new ShoppingList();

    shoppingList.addItem(new shoppinglist.ShoppingItem("milk", 0.99));
    shoppingList.addItem(new shoppinglist.ShoppingItem("butter", 1.99));

    assertEquals("milk", shoppingList.getItems().get(0).getName());
    assertEquals(Double.valueOf(0.99), shoppingList.getItems().get(0).getPrice());

    assertEquals("butter", shoppingList.getItems().get(1).getName());
    assertEquals(Double.valueOf(1.99), shoppingList.getItems().get(1).getPrice());
  }
}
