/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package todo;

import org.junit.Test;
import static org.junit.Assert.*;

public class TodoTest {
  public Todo todoList = new Todo();

  @Test
  public void todoStartsEmpty() {
    assertTrue("todo list is empty", todoList.getTasks().isEmpty());
  }

  @Test
  public void todoAddTask() {
    todoList.addTask("Do something");
    assertTrue("todo list has one item: do something", todoList.getTasks().get(0) == "Do something");
  }
}
