import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class MiddleLetters {

  public String getMiddleLetters(String inputString) {
    Integer lengthOfInput = inputString.length();
    String middleLetters;

    if (lengthOfInput % 2 == 0) {
      String letter1 = String.valueOf(inputString.charAt(lengthOfInput / 2 - 1));
      String letter2 = String.valueOf(inputString.charAt(lengthOfInput / 2));
      middleLetters = letter1 + letter2;
    } else {
      middleLetters = String.valueOf(inputString.charAt(lengthOfInput / 2));
    }
    return middleLetters;
  }

  public static void main(String[] args) {
    MiddleLetters middle = new MiddleLetters();
    Scanner sc = new Scanner(System.in);
    String userInput = "";

    while (!userInput.equals("quit")) {
      System.out.printf("> ");
      userInput = sc.nextLine();
      if (!userInput.equals("quit")) {
        System.out.println(middle.getMiddleLetters(userInput));
      }
    }
    sc.close();
  }
}
