/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package calculator;

import org.junit.Test;
import static org.junit.Assert.*;

public class CalculatorTest {
  @Test
  public void CalculatorHasAGreeting() {
    Calculator classUnderTest = new Calculator();
    assertNotNull("Calculator should have a greeting", classUnderTest.getGreeting());
  }

  @Test
  public void testAddsTwoAndTwo() {
    Calculator calc = new Calculator();
    assertEquals("2 + 2 should equal 4", Integer.valueOf(4), calc.add(2, 2));
  }
}
